### PR TITLE
Do not try to serialize NodeJSInstallation over Remoting, and fix test mocks

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Comment by jglick** [comment]
[INFRA-2739](https://issues.jenkins-ci.org/browse/INFRA-2739)

**Comment by nfalco79** [comment]
I have to test locally and manually if the information about platform is moved correctly to slave node with different O.S.

**Comment by jglick** [comment]
Right. I believe the refactoring preserved behavior, but there is no meaningful test coverage here; `NodeJSInstallationTest` passing does not prove much. The right thing to do would be to use `docker-fixtures` (or testcontainers.org) to actually launch an agent with a different filesystem layout, but node.js installed in the expected location, and actually run a build using it.

**Comment by nfalco79** [comment]
That kind of test it's to complicate and takes too much time during a normal build, requires tools in local pc.... When I touch Installation class I know I have perform this kind of test. This is true in any implementation of installation that have distribution for each OS ( for examole android, java)

**Comment by jglick** [comment]
> takes too much time during a normal build

How much time is too much? Typically <1m, more like 15s depending on caches.

> requires tools in local pc

Well, Docker yes, but that is pretty widespread by now. Tests like these will be automatically skipped if you have no `docker` executable. ci.jenkins.io can run such tests if you specify for example

```groovy
buildPlugin(platforms: ['docker', 'windows'])
```

**Comment by nfalco79** [comment]
@jglick I had test slave between different O.S. (master windows and slave linux raspberry) and seems to work as expected.
```
[node] $ /bin/sh -xe /tmp/jenkins7764782531485802072.sh
+ echo C:\Program Files\Java\jdk1.8.0/bin:/home/pi/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_raspberry/bin:C:\Program Files\Java\jdk1.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/games
C:\Program Files\Java\jdk1.8.0/bin:/home/pi/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_raspberry/bin:C:\Program Files\Java\jdk1.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/games
+ echo /home/pi/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_raspberry
/home/pi/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_raspberry
+ node -v
v15.4.0
```

The only strange thing is the PATH variable that contains a mix of windows and linux paths. In debug I see the NodeJS plugin code is OK.
There is a bug in OpenJDK/OracleJDK plugin that calculate the PATH+JAVA env variable based on the master platform and not the slave platform causing the issue in the PATH.

**Comment by jglick** [comment]
> There is a bug in OpenJDK/OracleJDK plugin that calculate the PATH+JAVA env variable based on the master platform and not the slave platform

Hmm. Feel free to report in `jdk-tool-plugin`.

**Pull request merged**
