### PR TITLE
Attempt to fix JENKINS-27170

### PR DESCRIPTION
**Pull request by kristofferpeterhansel**
So... I attempted to fix the mentioned issue by overwriting the path for the install command. At least on Linux it appears to work.

### CODE REVIEW

**Comment by unilama** [comment]
I sent updated version of this merge request in this pull https://github.com/kristofferpeterhansel/nodejs-plugin/pull/1 please review it :)

Thank you a lot :)

**Comment by kristofferpeterhansel** [comment]
Well. It looks like the changes @unilama made got the thing to build. And it still works in my test installation too.

**Comment by adam-knights** [comment]
@fcamblor or @cliffano any chance of a release with this included?

**Comment by fcamblor** [comment]
@adam-knights @ndeloof is working on another PR refreshing the implementation (see PR #8) for the installation

I'm wondering if it will be compatible with current PR and may fix it at the same time

I suppose he will make a release once he will have finished his work.. you might check before this release if the bug is fixed or not.

**Comment by ndeloof** [comment]
I indeed think the issue is related to the way PATH was initially hacked (not relying on `PATH+X` overrides, maybe just because you didn't know about it ?). With PR #8 you shouldn't have such issue, can you please give it a try ?

**Comment by adam-knights** [comment]
@ndeloof Awesome. Absolutely happy to try out PR 8 and see if I can get phantomjs installing, I've not devved or built a jenkins plugin before. Is there any chance of sharing the built file or linking me to some instructions to follow?

**Comment by kristofferpeterhansel** [comment]
So #8 is implementing this as well as some workflow support? If that is the case. Shouldn't this PR be closed for clarity?

**Comment by ndeloof** [comment]
You can test binary from https://jenkins.ci.cloudbees.com/job/plugins/job/nodejs-plugin/28/org.jenkins-ci.plugins$nodejs/artifact/org.jenkins-ci.plugins/nodejs/0.3-SNAPSHOT/nodejs-0.3-SNAPSHOT.hpi

@kristofferpeterhansel  #8 intent is not about this specific issue, but would like to know if it persists as I guess the rework of PATH management could have fixed it at same time - then should be closed (as well as related jira issue)

**Comment by adam-knights** [comment]
@ndeloof #8 does not fix phantomjs not installing. I get:

    > phantomjs@1.9.18 install /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/0.12.7/lib/node_modules/phantomjs
    > node install.js
    
    sh: 1: node: not found

    npm ERR! phantomjs@1.9.18 install: `node install.js`
    npm ERR! spawn ENOENT
    npm ERR! 
    npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.

You can reproduce by setting up as install automatically, select latest node from nodejs website and then in the 'global npm packages to install' add `phantomjs@1.9.18`. Run a job using the 'Provide Node & npm bin/ folder to PATH' option and the console will show the above

**Comment by ndeloof** [comment]
I get a distinct earlier error trying to reproduce this issue : 
```
Building in workspace /Users/nicolas/Boulot/jenkins-ci/nodejs-plugin/work/workspace/azr
Unpacking http://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz to /Users/nicolas/Boulot/jenkins-ci/nodejs-plugin/work/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest on Jenkins
$ /Users/nicolas/Boulot/jenkins-ci/nodejs-plugin/work/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest/bin/npm install -g phantomjs@1.9.18
module.js:338
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nicolas/Boulot/jenkins-ci/nodejs-plugin/work/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by fcamblor** [comment]
@ndeloof Maybe it's because you're trying to install a Mac OS X node installation which is not supposed to be supported by the plugin (I remember facing some issues on this 2 years ago... that's why I warned people that the plugin was not compatible with Mac nodes)

An issue exists though https://issues.jenkins-ci.org/browse/JENKINS-27845

**Comment by ndeloof** [comment]
I was able to reproduce this issue and provide a fix
https://github.com/ndeloof/nodejs-plugin/commit/f38e0a5d20a747d235dd1c439ebb92eef4b0fe8f

**Comment by adam-knights** [comment]
@ndeloof I can confirm that checking out and building https://github.com/ndeloof/nodejs-plugin/commit/f38e0a5d20a747d235dd1c439ebb92eef4b0fe8f fixed this for me - is that now going to be in https://github.com/jenkinsci/nodejs-plugin/pull/8?

**Comment by ndeloof** [comment]
yes, I'm waiting for code review to complete (to follow cloudbees contribution guidelines) and will merge

**Comment by adam-knights** [comment]
@fcamblor any chance of tagging a release with this code in? The plugin doesnt really work without it.

**Pull request closed without merging**
