### PR TITLE
Added another build step that executes GruntJs

### PR DESCRIPTION
**Pull request by ohanetz**
Added another build step that executes GruntJs based on given parameters, so user doesn't have to run grunt manually from the console.
In addition, while making this change, I added some changes to the code that will make it easier to add additional tasks in the future. I think more changes can be added in the future.

### CODE REVIEW

**Comment by fcamblor** [comment]
Hi,

I'm not a big fan of this design.
Because it provides some specificities (runnning grunt js command) whereas we should be able to install whatever npm package providing its own command line (`bower`, `grunt`, `gulp`, `cordova`, whatever)

Why provide some distinction for grunt and not the other possible commands ?
What is the added value of providing task runner compared to bash script line call (`grunt <target1> <target2> etc..`) ?

**Comment by ohanetz** [comment]
Hi,

The reason I added this change is that I only use grunt with jenkins with many builds and tasks, and using grunt as part of a shell execution cause my builds to be messy. I wanted to be able to change and add new configuration quickly, and monitor failures easily (tell exactly the failure point, not so intuitive when running shell script, need to manage return codes, maybe return strings).

That said, no reason why this shouldn't be done to other commands as well. Please note the small changes in the design (that can be taken 2-3 additional steps forward) that should make it easier creating build steps for additional tasks...


Omer

**Comment by fcamblor** [comment]
```
Using grunt as part of a shell execution cause my builds to be messy. I wanted to be able to change and add new configuration quickly, and monitor failures easily
```
I might understand this, but I don't see what your grunt run task has better (in terms of configuration & monitoring) than the standard `run bash command`.

Moreover, what I dislike here is the fact that the grunt task *assumes* grunt package is made available
If you don't provide any `grunt` executable to the job, the runner will fail won't it ?

To my POV, this is not a bad plugin idea, but I would create a dedicated gruntjs jenkins plugin for this.

**Comment by kristofferpeterhansel** [comment]
Actually don't this make sense in that it would make a job potentially more platform neutral? As currently you either select a windows or a (bash) shell to execute it in. Specific support for running something like this would allow the plugin to handle that.

**Comment by fcamblor** [comment]
@kristofferpeterhansel Did you try to run a `bash shell` build step under windows with the grunt command within it ?

I can't test it on my side, but I'm betting it should be ok.

If this is not the case, it is a good argument.

**Comment by kristofferpeterhansel** [comment]
As far as I can tell "Execute Shell" won't work on Windows by default as it generates an ".sh" file and tries to run that.

It's not really a need I personally have. I just noticed the PR and figured I'd point out there may be benefits that was maybe not part of the primary reason to implement this.

**Comment by ruckc** [comment]
any movement on this... trying to figure out how to do grunt tasks and i'm 2 hours in with 17 failed runs....

**Comment by nfalco79** [comment]
no movement on this, my POV is the same of **fcamblor**. The same goal can be reach with one command line (that is the purpose of this plugin):
> npm install grunt-cli --save-dev (if not provided in the installation NodeJS as global package)
> grunt

@kristofferpeterhansel if gruntfile can be invoked/loaded by javascript code, you can use "Execute script NodeJS" build step that is platform indipendent.

**Pull request closed without merging**
