### PR TITLE
Handle Sun OS platforms (such as solaris)

### PR DESCRIPTION
**Pull request by antoninBr**
Since node.js has a sun solaris install could it be possible to handle this sort of Platform in the jenkins nodejs-plugin ?

### CODE REVIEW

**Comment by antoninBr** [comment]
Before you ask : Yes, we must run our CI on a Solaris instance (we still manage to have Java Jdk8, Jenkins 2.93 and Sonar 6.7 LTS working on this thing...).

**Comment by nfalco79** [comment]
Do you have a sunos system where test these changes?

**Comment by nfalco79** [comment]
Please open a new feature in our JIRA system

**Comment by antoninBr** [comment]
Hello,
Actually I have a CI running on Sun Solaris sparc, so testing shouldn't be a problem...

**Comment by antoninBr** [comment]
New feature demand added on the Jira https://issues.jenkins-ci.org/browse/JENKINS-48456

**Comment by nfalco79** [comment]
The current PR seems doesn't generate the sunos archive link to download

**Pull request merged**
