### PR TITLE
Add Java 17 to build/test matrix

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
Used my admin powers to replay the build with the `Jenkinsfile` changes here: https://ci.jenkins.io/job/Plugins/job/nodejs-plugin/job/PR-103/2/

**Comment by nfalco79** [comment]
any reason for this? Is the jdk 17 the default for the latest version of jenkins?
I would keep Jenkinsfile as standard as possible

**Comment by basil** [comment]
> I would keep Jenkinsfile as standard as possible

The standard is defined in the archetype: https://github.com/jenkinsci/archetypes/blob/master/common-files/Jenkinsfile

This repository is not as standard as possible because it does not currently conform to the archetype.

This PR makes this repository conform to the archetype, thereby making it as standard as possible.

**Comment by basil** [comment]
Closing in favor of #107.

**Pull request closed without merging**
