### PR TITLE
introduced maven wrapper

### PR DESCRIPTION
**Pull request by grafjo**

### CODE REVIEW

**Comment by nfalco79** [comment]
This PR it is little bit unclear

**Comment by grafjo** [comment]
Hi @nfalco79,
this PR will add the [maven wrapper](https://github.com/takari/maven-wrapper) to this project.
So the project can be build like `./mvnw clean verify` and no explicit maven installation is required.

**Comment by imod** [comment]
👍 I was about to create the same PR too

**Comment by nfalco79** [comment]
I did not see anything similar in other plugin repo.
Anyway this will involve maintain update these scripts and fix potential bugs on them

**Comment by imod** [comment]
I don't think this is an issue... but up top you. It is the same thing a all gradle users are used to since a very long time.
Here is the documentation for the whole thing - https://github.com/takari/maven-wrapper

**Comment by nfalco79** [comment]
this PR is deprecated, other plugin just use this folder just to configure maven parameter like incremental build than use to run a maven build

**Pull request closed without merging**
