### PR TITLE
[FIX JENKINS-33698] NodeJS plugin npm install without root permissions

### PR DESCRIPTION
**Pull request by nfalco79**
For NodeJS >= 6.x version the "prefix" variable is relocated to local
installation tools folder as previous version. This settings could be
override using the npmrc file hierarchy. If a prefix variable is already
present in the default settings of local installation is kept.

### CODE REVIEW

**Comment by mplsbk** [comment]
When is this going to be merged and published? this is currently a blocker on my project.

**Comment by nfalco79** [comment]
I've not proceed to merge this fix and the reason is that the master branch code has update the way to contribuite environment variables. That is cool but if a new release will be released the plugin will not work if the [EnvInject](https://issues.jenkins-ci.org/browse/JENKINS-26583) plugin was installed.

But you have reason. I could ask to merge this fix in master but no release new one untill EnvInject will resolve [this PR](https://github.com/jenkinsci/envinject-plugin/pull/37)

**Comment by tfennelly** [comment]
Maybe you are already aware of this, but the plugin parent pom already contains maven profiles for the `frontend-maven-plugin`, which will add npm and node locally to your build. The older versions of the profiles assumed your build was using gulp, but 2.17 and after (if there's been one since) just run npm scripts ("mvnbuild" and mvntest).

Just Fyi ... maybe it does not help you !!

**Comment by nfalco79** [comment]
I use `frontend-maven-plugin` to build npm project as part of war project or to trasform web project into web bundle deployable in Java EE/OSGi container.
But this fix is needed to build all our pure npm (no gulp) project library and release it on our internal npm repo.
Our frontend programmers do not like embed their project into maven container.

tfennelly, thank for the tips

**Comment by nfalco79** [comment]
This PR is not needed.
Commit f38e0a5d20a747d235dd1c439ebb92eef4b0fe8f already close this issue. I will release a 0.2.2 with just that fix when they give me permission to deploy new release.

**Pull request closed without merging**
