### PR TITLE
Fix node PATH while installing npm

### PR DESCRIPTION
**Pull request by hdkshjm**
The jenkins job which depends on `NodeJS Plugin` and below other plugins, cannot finish successfully.(please see *1 error log)
* other plugins
  * https://wiki.jenkins-ci.org/display/JENKINS/pyenv+plugin
  * https://wiki.jenkins-ci.org/display/JENKINS/rbenv+plugin

Because, `NodeJS Plugin` override the `PATH`, so `pyenv plugin` cannot find the git command on `PATH` for installing pyenv.
* https://github.com/jenkinsci/nodejs-plugin/blob/19f5acc88fb1907adcfdf86e9d81ef901d3b8d62/src/main/java/jenkins/plugins/nodejs/tools/NpmPackagesBuildWrapper.java#L83-L86
* 
  ```
                String overriddenPaths = NodeJSInstaller.binFolderOf(nodeJSInstallation, build.getBuiltOn())
                        + pathSeparator
                        + vars.get("PATH");
                vars.override("PATH", overriddenPaths);
   ```

Instead of overriding `PATH`, this pr adds `"PATH+NODEJS"` to env like  https://github.com/jenkinsci/nodejs-plugin/commit/9a44fe8e046e6aaf85f5abcd45e006780c460dd5

### Jenkins Info
* Jenkins ver. 2.19.4
  * CentOS7
* NodeJS Plugin 0.2.2
* pyenv plugin 0.0.7
* rbenv plugin 0.0.16

### *1 error log 
* jenkins configuration 
* jenkins job log
```
Started by user 
[EnvInject] - Loading node environment variables.
Building remotely on slave-server in workspace /home/jenkins/jenkins_home/workspace/test_job
$ /home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/bin/npm install -g bower@~1.7.9 grunt-cli@~0.1.13 gulp@~3.9.1
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/bin/bower -> /home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/lib/node_modules/bower/bin/bower
/home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/bin/grunt -> /home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/lib/node_modules/grunt-cli/bin/grunt
/home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/bin/gulp -> /home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/lib/node_modules/gulp/bin/gulp.js
/home/jenkins/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/6.9.4LTS/lib
├── bower@1.7.9 
├── grunt-cli@0.1.13 
└── gulp@3.9.1 

$ bash -c "[ -d \$HOME/.pyenv ]"
Installing pyenv...
$ bash -c "git clone https://github.com/yyuu/pyenv.git \$HOME/.pyenv && cd \$HOME/.pyenv && git checkout master"
bash: git: command not found
FATAL: (CommandError) failed: "git clone https://github.com/yyuu/pyenv.git \\$HOME/.pyenv && cd \\$HOME/.pyenv && git checkout master"
org.jruby.exceptions.RaiseException: (CommandError) failed: "git clone https://github.com/yyuu/pyenv.git \\$HOME/.pyenv && cd \\$HOME/.pyenv && git checkout master"
	at RUBY.run(/home/jenkins/jenkins_home/plugins/pyenv/WEB-INF/classes/lib/pyenv/invoke.rb:18)
	at RUBY.install!(/home/jenkins/jenkins_home/plugins/pyenv/WEB-INF/classes/lib/pyenv.rb:47)
	at RUBY.setup!(/home/jenkins/jenkins_home/plugins/pyenv/WEB-INF/classes/lib/pyenv.rb:20)
	at RUBY.setup(/home/jenkins/jenkins_home/plugins/pyenv/WEB-INF/classes/models/pyenv_wrapper.rb:57)
	at RUBY.setUp(/home/jenkins/jenkins_home/plugins/pyenv/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/model/environment_proxy.rb:8)
Finished: FAILURE
```

### CODE REVIEW

**Comment by nfalco79** [comment]
Thank for the patch, the issue was fixed in master long time ago but not released.
In 0.2.x branch that way to setup PATH permit NodeJS to works also when envinject plugin is installed (see JENKINS-26583). Release a 0.2.3 with this patch will cause a lot new issues.

Be patient, ASAP (when I found a workaround to JENKINS-26583) I will release the 1.0

**Comment by hdkshjm** [comment]
> In 0.2.x branch that way to setup PATH permit NodeJS to works also when envinject plugin is installed (see JENKINS-26583). Release a 0.2.3 with this patch will cause a lot new issues.


OK.

I have a question.
On below commit, you use override `"PATH+NODEJS"`, not put.
* https://github.com/jenkinsci/nodejs-plugin/blob/06c1c1b56865bdf93dad79b5440e822ec680191b/src/main/java/jenkins/plugins/nodejs/tools/NodeJSInstallation.java#L70-L71
  ```
  //        env.put("PATH+NODEJS", getBin()); // TODO enable this instead override when JENKINS-26583 is fixed
          env.override("PATH+NODEJS", getBin());
  ```


On this pr, instead of `vars.put("PATH+NODEJS", nodeJSPath);`, is it better to use `vars.override("PATH+NODEJS", nodeJSPath);`?
Or should I close this pr?

**Comment by nfalco79** [comment]
This PR point to support 0.2 branch used to release an important hotfix when master there was too changes.
Next releases will be performed on master and no more on support 0.2 branch, so this PR can be closed.

About your question: depends:
- in case if SimpleBuilderWrapper you have _jenkins.tasks.SimpleBuildWrapper.Context_ where there put = override
- in the other cases on _hudson.EnvVars_ you have both put and override. Here put not do override.

In my case NodeJSBuilder it's a SimpleBuilderWrapper (then Context), instead NodeJSCommandInterpreter is a Builder (then EnvVars)

**Comment by hdkshjm** [comment]
Thanks for your information.
I close this issue.

**Pull request closed without merging**
