### PR TITLE
Add latest Node 16

### PR DESCRIPTION
**Pull request by robcalcroft**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by robcalcroft** [comment]
Trying to download latest node 16 with `nodejs_16_13_2` but its erroring and i cant see the error but `nodejs_14_17_1` works ok as version, not sure if i got syntax or if there is another issue why i cant use node 16?

**Comment by nfalco79** [comment]
you are changing a resource for a test case. That resource does not list all possible URls because otherwise it takes too much time. What is here the improvements?

**Comment by robcalcroft** [comment]
Ah! Apologies we can close this as i thought this was adding v16 support or something. Do you know why 
```
stage('Install dependencies') {
      steps {
        nodejs(nodeJSInstallationName: 'nodejs_16_13_2') {
          sh 'npm ci'
        }
      }
    }
```
wouldn't work when using `nodejs_14_17_1` works totally fine?

**Comment by nfalco79** [comment]
In our Jenkins I see NodeJS 16.xyz. Tools combobox is popuate with the content of [tihs file](https://updates.jenkins-ci.org/current/updates/hudson.plugins.nodejs.tools.NodeJSInstaller.json). Verify this file updated in $JENKINS_HOME/updates. If not see log why the file failed to download and or update manually than restart Jenkins.

**Pull request closed without merging**
