### PR TITLE
Modified the NodeJS Image URL evaluation logic.

### PR DESCRIPTION
**Pull request by shawnda761**
Moved NodeJS Image URL evaluation logic from 'LatestInstallerPathResolver.java' to 'NodeJSInstaller.java', and changed it to evaluate if the URL is reachable.

### CODE REVIEW

**Comment by nfalco79** [comment]
I do not want rely on connection to say if a NodeJS architecture and platform is supported or not. Connection is too instable.

**Comment by shawnda761** [comment]
I agree that evaluate the connection is not a good idea. How about add some configuration items to deal with those version limitations to alter current hard coding. Actually, I did this change just because I always got some error when I tried to use several 12+ versions NodeJS in a Linux arm64 machine. So I read the code and noticed some limitations in it (LatestInstallerPathResolver.java around line 118).

**Comment by nfalco79** [comment]
If there is error where some combo (CPU+platform) seems not be supported but should in LatestInstallerPathResolver than please fill a new defect (for this specific issue) and propose a patch for LatestInstallerPathResolver to respect the real supported distribution. Something that limitation could e also dictated that the distribution exists but does not work for sure. That behaviour has been inherited from previous mantainer (the creator of this plugin) and I would change it unless I see a good mantanaible alternative to support actuals scenarios

**Comment by nfalco79** [comment]
just an example the Apple Silicon has been recogneze as aarch64 -> arm64 and platform MacOs -> darwin
In this case you could (not official for what I know) use the linux arm64 binary. Maybe there will not be available a specific distribution node-v15.7.0-darwin-arm64.tar.gz available for a long time. The LatestInstallerPathResolver can map given as input arm64 darwin to the linux distribution node-v15.7.0-linux-arm64.tar.gz

I confirm that the switch in LatestInstallerPathResolver is wrong and handle arm64 like arm6l where the support has been removed from version >=12. The switch case for arm64 should handle if platform == linux and version >= 4 than it's ok

**Comment by shawnda761** [comment]
Got it. Totally agree. BTW, would you mind deleting line 125 and 126 in that file for me if you make any change in the future? Forgive me for being such a neat freak.

**Pull request closed without merging**
